config/routes.rb
class DomainConstraint
  def initialize

  end

  def matches?(request)

    Site.find_by_name(request.subdomain)
  end
end

Rails.application.routes.draw do

  if Rails.env.production?
    Rails.application.routes.default_url_options[:host]= 'photobaron.info'
  else
    Rails.application.routes.default_url_options[:host]= 'adibaron.com:5000'
  end

  constraints(DomainConstraint.new) do
    get '*route', to: 'sites#show' # handle all routes
    get '', to: 'sites#show' # handle root of subdomain
  end

  devise_for :users,
    :controllers => { :registrations => "users/registrations",
                      :sessions => "users/sessions",
    }

  resources :accounts, controller: 'accounts'

  resources :sites
  resources :images
  resources :rooms do
    collection do
      get   :search
      post  :search
    end
  end

  resources :sites do
    resources :images
    resources :rooms do
      collection do
        get   :search
        post  :search
      end
    end
  end

  resources :welcome
  root 'welcome#index', constraints: { subdomain: /^$|^www/ } # subdomain empty string or www

end

app/views/shared/_language_dropdown.html.erb
<div class="dropdown" style="float:right; height:100%; margin:0px; line-height:25px;">

  <button class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" style="background:none; border:none; color:white;">
    <span class="lang-sm" style="margin-top:5px;" lang="<%= current_language %>" >  </span> &nbsp;
    <span> <%= current_language %> </span>
    <span class="caret"></span>
  </button>

  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  	<% languages_dic.each do |key, val| %>
  		<li>
  			<%= link_to val, '#', :data => { :language => key, }, :onclick => "set_language(this);" %>
  		</li>
  	<% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="container-fluid navbar-fixed-top site-header" style="z-index:101;">
  <div class="container">
    <div class="row" style="height:25px; line-height:25px;">
      <%= render "shared/language_dropdown" %>
    </div>
  </div>
</div>

<nav class="navbar navbar-default navbar-fixed-top site-menu" style="top:25px; z-index:100;">
  <!-- <div class="container-fluid"> -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#" style="padding-left:5px;">Picndo Sites</a> -->
        <%= link_to "Picndo Sites", {controller: "welcome", action: "index"}, class: "navbar-brand", style: "padding-left:5px;"%>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav" style="float:none;">
          <%= render 'navbar_list' %>
          <% if current_user %>
            <li class="dropdown" id="menuLogin" style="position:static; float:right;">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">
                <%= t('.hi')%> <%= current_user.profile.nil_or.full_name.nil_or.titleize || current_user.email %>
                <span class="caret"> </span>
              </a>
              <div class="dropdown-menu" style="width:100%;">
                <div class="container-fluid" style="padding-top:0px;">
                  <%= render "shared/user_dropdown" %>
                </div>
              </div>
            </li>
          <% else %>
            <li class="dropdown" id="menuLogin" style="position:static; float:right;">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">
                <%= t('.login')%>
                <span class="caret"> </span>
              </a>
              <div class="dropdown-menu" style="width:100%;">
                <div class="container" style="padding-top:0px;">
                  <div class="col-sm-4" style="float:right;">
                    <h2><%= t('.login')%></h2>
                    <%= render :file => 'users/sessions/new' %>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_user_dropdown.html.erb
<div class="row">
	<div class="col-sm-4" style="float:right; font-size:16px; color:#333;">
		<%= render "shared/user_sites" %>
		<br>
	</div>
</div>

app/views/shared/_user_sites.html.erb
<%= link_to("View Your Profile", account_path(current_user.id), :class => "btn btn-primary", :style => "") %>
<%= link_to("Log Out", destroy_user_session_path, :style => "font-size:14px; color:blue !important; margin-left:10px;") %>

<h3> Your Sites </h3>
<ul style="list-style-type: none; padding:0px;">
	<% current_user.sites.each do |s| %>
		<li>
			<%= s.name %>
			<%= link_to("Edit Site", [:edit, s], :target => "_blank", :class => "btn btn-sm btn-primary", :style => "color:white !important; font-size: 14px; border-right:1px solid:#333;") %>
			|
			<%= link_to("View Site", s, :target => "_blank", :class => "btn btn-sm btn-primary", :style => "color:white !important; font-size: 14px;") %>
		</li>
	<% end %>
</ul>